# Compiler
CXX = g++

# Compiler Flags
CXXFLAGS = -std=c++17 -Wall -Wextra -O2

# Libraries
LIBS = -lssl -lcrypto -lz

# Source Files
SRC = main.cpp blob.cpp init.cpp helper.cpp tree.cpp checkout.cpp add.cpp commit.cpp log.cpp

# Header Files
HEADERS = headers.h

# Output Executable
TARGET = mygit

# Build Rules
all: $(TARGET)

$(TARGET): $(SRC) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LIBS)

# Clean up build artifacts
clean:
	rm -f $(TARGET)
	rm -f *.o

# Run
run: $(TARGET)
	./$(TARGET)

